# Generated by Django 5.1.1 on 2024-11-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="date",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
